### ISSUE TITLE
可否去掉反链面板与正文的分隔线

### ISSUE THREAD

**Issue by TinkMingKing** [Misuzu2027/syplugin-backlink-panel#17]
![image](https://github.com/user-attachments/assets/8d0fa68b-2fe5-404a-8a5d-4e71e887f6aa)

那根黑线显得太突兀，面板本身颜色与背景就不一样，不像RR那种与背景融为一体，所以分隔线是不必要的

**Comment by Misuzu2027** [comment]
可以用 css 进行隐藏：
```css
div.backlink-panel-document-bottom__area > hr{
  display:none;
}
```
