### ISSUE TITLE
可不可以增加一个开关，可以选择不显示筛选面板

### ISSUE THREAD

**Issue by Kikkwa** [Misuzu2027/syplugin-backlink-panel#30]
您的插件做的非常好看，只是我对功能的需求很低，只是想看到反链面板，使用筛选的情况比较少

**Comment by Misuzu2027** [comment]
筛选面板是核心功能，不打算增加隐藏开关。

不过可以在插件设置中：筛选面板 -> 默认展开筛选面板  取消勾选，就会默认折叠筛选面板，这样不会太占空间。

如果是想要完全隐藏筛选面板也是可以通过 CSS 代码片段做到的：
```css
.backlink-panel__area > .backlink-panel__header:first-of-type,
.backlink-panel__area > .backlink-panel-filter {
    display: none;
}
```
